version: "3.8"

services:
  db-x:
    build:
      context: .
    volumes:
      - ./:/api
    env_file: ".env"
    ports:
      - "6400:6400"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - "discovery.type=single-node"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail 0.0.0.0:9200/_cluster/health || exit 1"
        ]
      interval: 10s
      timeout: 30s
      retries: 3
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.10.1
    container_name: kibana
    platform: linux/amd64
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      TELEMETRY_ENABLED: false
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  esdata: